In [1]:
import re
import numpy as np
from collections import Counter
from scipy.spatial import distance
text = open('sentences.txt','r')
massiveOfLines = []
massiveOfSplitedLines = []
for line in text.read().splitlines():
    massiveOfLines.append(line.lower())
#print(massiveOfLines)
for line in massiveOfLines:
    SplitedLine = re.split('[^a-z]', line)
    SplitedLine = [x for x in SplitedLine if x]
    massiveOfSplitedLines.append(SplitedLine)
#print(massiveOfSplitedfLines)
flat_list = [item for sublist in massiveOfSplitedLines for item in sublist]
dict = Counter(flat_list)
my_dict = {}
listOfUniqWords = list(set(flat_list))
i = 0
for word in listOfUniqWords:
    my_dict[i] = listOfUniqWords[i]
    i += 1
    
#print(len(a))
#print(len(my_dict.keys()))
#print(my_dict)

main_array = np.zeros((len(massiveOfLines), len(my_dict.keys())))
i = 0
j = 0

#print(main_array)
while i <  len(massiveOfSplitedLines):
    while j < len(my_dict.keys()):
        main_array[i,j] = massiveOfSplitedLines[i].count(my_dict[j])
        #print( main_array[i,j])
        j += 1
    j = 0
    i += 1
i = 0
for line in main_array:
    print(i,'   ',distance.cosine(main_array[0], line))
    i += 1

0     0.0
1     0.9527544408738466
2     0.8644738145642124
3     0.8951715163278082
4     0.7770887149698589
5     0.9402385695332803
6     0.7327387580875756
7     0.9258750683338899
8     0.8842724875284311
9     0.9055088817476932
10     0.8328165362273942
11     0.8804771390665607
12     0.8396432548525454
13     0.8703592552895671
14     0.8740118423302576
15     0.9442721787424647
16     0.8406361854220809
17     0.956644501523794
18     0.9442721787424647
19     0.8885443574849294
20     0.8427572744917122
21     0.8250364469440588


In [158]:
print(my_dict)

{0: 'disk', 1: 'adjacent', 2: 'from', 3: 'place', 4: 'unix', 5: 'major', 6: 'not', 7: 'genes', 8: 'switch', 9: 'lb', 10: 'streams', 11: 'stdin', 12: 'mice', 13: 'patch', 14: 'tamed', 15: 'successor', 16: 'just', 17: 'sequence', 18: 'redirection', 19: 'type', 20: 'instead', 21: 'also', 22: 'where', 23: 'left', 24: 'factory', 25: 'deliberately', 26: 't', 27: 'safari', 28: 'separate', 29: 'information', 30: 'command', 31: 'if', 32: 'ancestor', 33: 'mountain', 34: 'standard', 35: 'you', 36: 'now', 37: 'july', 38: 'ears', 39: 'editions', 40: 'three', 41: 'members', 42: 'longer', 43: 'clear', 44: 'yosemite', 45: 'second', 46: 'be', 47: 'learned', 48: 'its', 49: 'drive', 50: 'closest', 51: 'os', 52: 'wrong', 53: 'kg', 54: 'delete', 55: 'and', 56: 'on', 57: 'time', 58: 'artificial', 59: 'concatenate', 60: 'too', 61: 'were', 62: 'interactive', 63: 'any', 64: 'content', 65: 'stdout', 66: 'high', 67: 'typically', 68: 'chromosomes', 69: 'using', 70: 'lion', 71: 'over', 72: 'genus', 73: 'files', 74

In [99]:
?np

In [4]:
print(main_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
